<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/StickyNotes.ico</ApplicationIcon>
    <Version>0.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="StickyNotes.Tests" />
    <Resource Include="Assets/StickyNotes.ico" />
    <ProjectReference Include="../StickyNotes.Core/StickyNotes.Core.csproj" />
    <PackageReference Include="Markdig" Version="0.37.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
